version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /var/www/html
    pattern: "*"
    owner: apache
    group: apache
    mode: 744
    type:
      - file
  - object: /var/www/html
    pattern: "*"
    owner: apache
    group: apache
    mode: 744
    type:
      - directory
hooks:
  ApplicationStop:
    - location: deploy-script/Stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy-script/Start.sh
      timeout: 300
      runas: root
